# based on recipe in
# https://github.com/jupyterlab/extension-cookiecutter-ts/blob/master/.travis.yml
language: python
sudo: false
dist: trusty
cache:
  pip: true
  directories:
    - $HOME/.npm
install:
- pip install -U -q pip
- pip install -q -U notebook
- pip install --pre -U jupyterlab
script:
- npm install
- npm run build
- jupyter labextension install .
- jupyter lab clean
- jupyter labextension link .
- python -m jupyterlab.browser_check
